#!/bin/zsh
# This will prepare the example for serving via github.
# This will:
# * Compile the javascript code
# * Fix the packages folder in example

ROOT_FOLDER=${0:A:h}
SOURCE_FOLDER=${ROOT_FOLDER}/example
BUILD_FOLDER=${ROOT_FOLDER}/build
TARGET_FOLDER=${SOURCE_FOLDER}/out

function clean () {
    [ -e ${BUILD_FOLDER} ] && rm -rf ${BUILD_FOLDER}
    [ -e ${TARGET_FOLDER} ] && rm -rf ${TARGET_FOLDER}
    pub install && pub update
}

function compile_javascript () {
    (
        cd ${ROOT_FOLDER}
        pub build --output ${BUILD_FOLDER} --mode ${1} example
    )
}

function fix_layout () {
    # The build generates a ${BUILD_FOLDER}/example which is a rough duplicate
    # of the example folder. The packages for this is directly within, but the
    # code that uses them is within web. So things must be moved.

    [ -e ${TARGET_FOLDER} ] && rm -rf ${TARGET_FOLDER}
    mv ${BUILD_FOLDER}/example/web ${TARGET_FOLDER}
    mv ${BUILD_FOLDER}/example/packages ${TARGET_FOLDER}

    rm -rf ${BUILD_FOLDER}
    rm ${SOURCE_FOLDER}/packages
}

clean
compile_javascript ${1:-release} && fix_layout

# vim: set ai et sw=4 syntax=zsh :
